version: "3"
services:
  nodered: 
    build: ./nodered
    image: localbuild/nodered
    container_name: nodered
    restart: unless-stopped
    ports: 
      - "1880:1880"
    volumes:
      - ./nodered/flows.json:/data/flows.json
      - noderedData:/data
    networks:
      - edge
  grafana:
    build: ./grafana
    image: localbuild/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "2301:3000"
    volumes: 
      - grafanaData:/var/lib/grafana
    networks:
      - edge
  influxdb:
    build: ./influx
    image: localbuild/influxdb
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: MAIER
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: vincent
      INFLUXDB_ADMIN_PASSWORD: test
      INFLUXDB_USER: richard
      INFLUXDB_USER_PASSWORD: test
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge
  mosquitto:
    build: ./mosquitto
    image: localbuild/mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports: 
      - "8883:1883"
      - "9001:9001"
    volumes: 
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge
#Create internal link network for Containers
networks:
  edge:

#Create Volumes for persistent Storage
volumes:
  grafanaData:
  noderedData:
  influxData:
  mosquittoLog:
  mosquittoData: